// <auto-generated />
using System;
using ContextoExamen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContextoExamen.Migrations
{
    [DbContext(typeof(ContextoExamen))]
    [Migration("20230914074912_listapersonas")]
    partial class listapersonas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaNacimiento = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Telefono = "123-456-7891"
                        },
                        new
                        {
                            Id = 2,
                            FechaNacimiento = new DateTime(1995, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            Telefono = "123-456-7892"
                        },
                        new
                        {
                            Id = 3,
                            FechaNacimiento = new DateTime(1990, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            Telefono = "123-456-7893"
                        },
                        new
                        {
                            Id = 4,
                            FechaNacimiento = new DateTime(1985, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Telefono = "123-456-7894"
                        },
                        new
                        {
                            Id = 5,
                            FechaNacimiento = new DateTime(1980, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis",
                            Telefono = "123-456-7895"
                        },
                        new
                        {
                            Id = 6,
                            FechaNacimiento = new DateTime(1975, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura",
                            Telefono = "123-456-7896"
                        },
                        new
                        {
                            Id = 7,
                            FechaNacimiento = new DateTime(1970, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Telefono = "123-456-7897"
                        },
                        new
                        {
                            Id = 8,
                            FechaNacimiento = new DateTime(1965, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Elena",
                            Telefono = "123-456-7898"
                        },
                        new
                        {
                            Id = 9,
                            FechaNacimiento = new DateTime(1960, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Isabel",
                            Telefono = "123-456-7899"
                        },
                        new
                        {
                            Id = 10,
                            FechaNacimiento = new DateTime(1955, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "David",
                            Telefono = "123-456-7800"
                        },
                        new
                        {
                            Id = 11,
                            FechaNacimiento = new DateTime(1950, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sofía",
                            Telefono = "123-456-7801"
                        },
                        new
                        {
                            Id = 12,
                            FechaNacimiento = new DateTime(1945, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pablo",
                            Telefono = "123-456-7802"
                        },
                        new
                        {
                            Id = 13,
                            FechaNacimiento = new DateTime(1940, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carmen",
                            Telefono = "123-456-7803"
                        },
                        new
                        {
                            Id = 14,
                            FechaNacimiento = new DateTime(1935, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "José",
                            Telefono = "123-456-7804"
                        },
                        new
                        {
                            Id = 15,
                            FechaNacimiento = new DateTime(1930, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Rosa",
                            Telefono = "123-456-7805"
                        },
                        new
                        {
                            Id = 16,
                            FechaNacimiento = new DateTime(1925, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Javier",
                            Telefono = "123-456-7806"
                        },
                        new
                        {
                            Id = 17,
                            FechaNacimiento = new DateTime(1920, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Paula",
                            Telefono = "123-456-7807"
                        },
                        new
                        {
                            Id = 18,
                            FechaNacimiento = new DateTime(1915, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miguel",
                            Telefono = "123-456-7808"
                        },
                        new
                        {
                            Id = 19,
                            FechaNacimiento = new DateTime(1910, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Cristina",
                            Telefono = "123-456-7809"
                        },
                        new
                        {
                            Id = 20,
                            FechaNacimiento = new DateTime(1905, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Roberto",
                            Telefono = "123-456-7810"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
